joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 125

joint_traj_controller:
  type: position_controllers/JointTrajectoryController

  joints: 
  - joint_1
  - joint_2
  - joint_3
  - joint_4
  - joint_5
  - joint_6
  - joint_7

  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    joint_1: {trajectory: 0.2, goal: 0.1}
    joint_2: {trajectory: 0.2, goal: 0.1}
    joint_3: {trajectory: 0.2, goal: 0.1}
    joint_4: {trajectory: 0.2, goal: 0.1}
    joint_5: {trajectory: 0.2, goal: 0.1}
    joint_6: {trajectory: 0.2, goal: 0.1}
    joint_7: {trajectory: 0.2, goal: 0.1}

  stop_trajectory_duration: 0.5
  state_publish_rate: 125
  action_monitor_rate: 20

gripper_controller:
  type: position_controllers/JointGroupPositionController

  joints: 
  - gripper_joint_l
  - gripper_joint_r